version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_network

  aspnet_app:
    build:
      context: ./AspNetApp
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    container_name: aspnet_app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app_network
    depends_on:
      - jenkins

networks:
  app_network:
    driver: bridge

volumes:
  jenkins_home: 